### ISSUE TITLE
Quyết định technical (2017/07/30)

### ISSUE THREAD

**Issue by mdshun** [On-The-Runway/orange#14]
# Quyết định teachnical cho hệ thống, 

Trình bày cả lí do chọn

**Comment by tranhuycong** [comment]
front-end: react. phù hợp mới các mô hình dự án lớn, khả năng quản lí và tái sử dụng cao. Cộng đồng đông đảo do fb phát triển tương lai tiếp tục được hỗ trợ. 
backend: nodejs(Express + socket). Cùng sử dụng cú pháp javascript. Dễ dàng tích hợp với thư viện socket để xử lí realtime. Hiệu năng khá tốt.
mobile-app: react-native. Dễ dàng chuyển đổi từ web-client sang mobile-app do cùng một mô hình phát triển. react-native hỗ trợ build đa nền tảng.
data: mysql. Dễ quản lí.

**Comment by hoangvantuan** [comment]
http://webfaver.com/nodejs/huong-dan-tao-ung-dung-chia-se-hinh-anh-voi-nodejs-socket-io-va-expressjs.html
