### ISSUE TITLE
Tạo biểu đồ di chuyển màn hình

### ISSUE THREAD

**Issue by mdshun** [On-The-Runway/orange#16]
# Biểu đồ di chuyển màn hình

VD: Từ một màn hình có thể di chuyển đến màn hình nào

**Comment by hoangtuan1401** [comment]
Cái này nên làm danh sách chức năng trước rồi mới tạo được sơ đồ,ae nghĩ nên dựa vào cái sơ đồ Requiment để làm và bổ xung

**Comment by hoangvantuan** [comment]
Ừm phần này sẽ làm sau khi phân tích xong mà
