### ISSUE TITLE
Quyết định danh sách màn hình

### ISSUE THREAD

**Issue by mdshun** [On-The-Runway/orange#17]
# Quyết định danh sách màn hinh

ps: Màn hình có trong hệ thống

**Comment by hoangtuan1401** [comment]
Theo ae thì màn hình chia làm 2 trạng thái:Chưa đăng nhập và đã đăng nhập
-Chưa đăng nhập thì có thể xem được các NSX và sản phẩm của các NSX nhưng bị hạn chế một số thông số như contact,giá,...nếu muốn hiển thi các thông số này thì phải đăng nhập
-Màn hình sau đăng nhập:chia làm 2 phần đó là NSX và đại lý,trong từng phần có các chỉ mục sẽ được nghiên cứu và bổ xung tiếp

**Comment by hoangvantuan** [comment]
Trạng thái thì đúng rồi. nhưng đây là danh sách màn hinh hình mà. Còn còn để truy cập được vào màn hình ấy hay không, hay có thể xem được cái gì trong màn hình ấy thì liên quan đến role (VD; User, Admin) ấy
