### ISSUE TITLE
Tạo tài liệu mô tả Ngiệp vụ (2017/08/06)

### ISSUE THREAD

**Issue by mdshun** [On-The-Runway/orange#21]
# Tạo tài liệu mô tả nghiệp vụ
_Tham khảo: Lược đồ BFD, DFD: Data Flow Diagram, IDEF0_

**Comment by hoangvantuan** [comment]
@hoangtuan1401 https://kipalog.com/posts/Thiet-ke-database-MySQL-tu-con-so-0
