### ISSUE TITLE
Tìm hiểu role trong hệ thống (2017/08/04)

### ISSUE THREAD

**Issue by mdshun** [On-The-Runway/orange#24]
# Tìm hiểu role trong hệ thống

**Comment by hoangvantuan** [comment]
# Owner
# Agency
# Provider
# Shipper

**Comment by hoangtuan1401** [comment]
Để ae viết phần này nhé!

**Comment by hoangvantuan** [comment]
ừm, xong cái requirement chưa

**Comment by hoangvantuan** [comment]
@hoangtuan1401 Over 4 ngày rồi tuấn ơi

**Comment by hoangtuan1401** [comment]
Hôm trước ae  viết 1 bản rồi nhưng giờ thấy bất cập.Hai cái 
Agency: Các đại lí phân phối.

Provider: Các nhà cung cấp
nó bị dẫn chân nhau quá,cụ thể thằng nào to hơn thằng nào và hiểu ở  2 cái này chưa đúng 
Giờ mình đang làm phân quyền theo kiểu công ty chứ không phải phân quyền theo các bên chức năng

**Comment by hoangtuan1401** [comment]
Ae mạnh dạn viết phân quyền kiểu này:
OWNER
MANAGER
LEADER
STAFF
SHIP

**Comment by hoangtuan1401** [comment]
Nếu đây là 1 nhà sản xuất nhỏ thì thằng OWNER + MANAGER là 1,vì thường thằng chủ sẽ là thằng trực tiếp quản lý lãnh đạo luôn.
Tiếp đó 3 thằng Leader + Staff lại làm chung việc,chung nhiệm vụ và khó phân chi tiết ra được
Có thể có thằng ship hoặc không,thằng Staff thấp cổ bé họng có thể bị làm ship

**Comment by hoangtuan1401** [comment]
Nhà sản xuất to hơn tý thì vai trò của thằng OWNER nó tách biệt tý,lúc này thì mới manh nha thằng MANAGER(kiểu như đốc công với giám sát ấy)
Leader + Staff vẫn chung nhiệm vụ,Ship đã là 1 thằng riêng không phải là Staff nữa.

**Comment by hoangtuan1401** [comment]
![image](https://user-images.githubusercontent.com/30333390/29067657-b4a66928-7c5d-11e7-8f29-45f537954bc4.png)
Còn cái này ae hiểu sẽ là mô hình kết nối giữa NSX - Đại Lý -Vận Chuyển hơn,lúc đó mình lại phải chia quyền của từng thằng

**Comment by hoangvantuan** [comment]
Ae viết được mô hình kết nối ra không.

**Comment by hoangtuan1401** [comment]
![image](https://user-images.githubusercontent.com/30333390/29067885-aef9c49c-7c5e-11e7-90e3-b7ff1413243e.png)
đây là bản cũ mà ae viết

**Comment by hoangvantuan** [comment]
@hoangtuan1401  Done thằng này nhé

**Comment by hoangtuan1401** [comment]
@hoangvantuan uhm,tài liệu ae viết xong sẽ up lên trên kia
