### ISSUE TITLE
Hạn chế việc gửi dữ liệu lên server bằng tool

### ISSUE THREAD

**Issue by mdshun** [On-The-Runway/orange#25]
# Hạn chế việc gửi dữ liệu lên server bằng tool
- Sử dụng token (mã hóa) để kiểm tra dữ liệu gửi lên server là tool hay do người dùng sử dụng trình duyệt (VD nút ).

**Comment by hoangvantuan** [comment]
http://how.vndemy.com/web-devel/821-tong-hop-11-bien-phap-bao-mat-ve-lap-trinh-an-toan-trong-phat-trien-ung-dung-web-p1/
