### ISSUE TITLE
Vấn đề về quản lí các sản phẩm bán lẻ 

### ISSUE THREAD

**Issue by mdshun** [On-The-Runway/orange#4]
Trường hợp đại lí vừa cung cấp sản phẩm cho đại lí cấp dưới vừa bán lẻ. Trong khi bán lẻ được phân ra làm 2 phần bán lẻ online và bán lẻ trực tiếp .

Vấn đề gặp phải ở đây là những mặt hàng bán lẻ trực tiếp không thể quản lí được --> làm sao để giải quyết vấn đề này ?

**Remarks:** Hiện nay ở việt nam việc bán lẻ hầu như là trao tay và không có hóa đơn,

**Comment by huynhnv1993** [comment]
Các sản phẩm đều phải nhập vào hệ thống, có giá nhập giá bán , etc...
Trực tiếp or Online thì đều là bán hàng -> đều phải đưa thành order vào hệ thống. 2 action trên đều sẽ có process của nó. Ví dụ:
Trực tiếp: sẽ do nhân viên tạo order -> process thanh toán -> etc.
Online: khách hàng trực tiếp tạo order -> process thanh toán -> etc.

**Comment by hoangvantuan** [comment]
@huynhnv1993  
Vấn đề là hiện nay ở việt nam bán lẻ hầu như không được nhập vào hệ thống 
Vì khi bán trực tiếp thường không có order cho khách lẻ. 

Khách hành mình hướng tới bao gồm cả các đại lí tư nhân ( tự mở) ví dụ như một cửa hàng

**Comment by tranhuycong** [comment]
Việc bán lẻ kiểu này chỉ thống kê khi người bán kiểm kê hàng được thôi chứ không ai đi nhập liệu liên tục được. Ngay cả nhập liệu khi thống kê hàng cũng có thể gây mất thời gian cho người dùng rồi. Tốt nhất có chức năng ghi lại số hàng sau kiểm kê để thống kê lại thôi

**Comment by hoangvantuan** [comment]
ừm, cái phần bán lẻ này khó kiểm soát đấy

**Comment by hoangtuan1401** [comment]
vấn đề ở đây là thói quen bán hàng chứ không phải là không được nhập vào hệ thống.Như thấy những cửa hàng thuê nhân viên bán hàng ấy,khi nhân viên bán bất cứ 1 sản phẩm gì đều ghi lại tên +giá vào sổ (mặc dù nó thủ công nhưng cũng coi như đây là việc nhập liệu vào hệ thống).Việc của mình đó là làm sao cho việc nhập liệu đó đơn giản nhất và tốn ít thời gian nhất.Khi làm cho nó dễ và tạo được thói quen thì ok thôi

**Comment by hoangvantuan** [comment]
Ừm cũng là một ý. phần này hay đấy nếu đơn giản hóa được các thao tác. Vì nếu đông khách (như tết hay lễ chẳng hạn thì chạy cong mông lên ấy chứ :)))
